server {
	listen 8081;
	server_name mediaplayer;

	root /home/pi/mp3frontend;
	index index.html;

	location ~ /\. {
		deny all;
	}

	location / {
		try_files $uri /index.html;
	}

	location /api/ {
		limit_req zone=music_api burst=60 nodelay;
		limit_conn music_conn 20;

		proxy_pass http://127.0.0.1:8080/api/;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
